# Generated by Django 5.0.6 on 2026-06-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('max_price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('avg_price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('trend', models.CharField(choices=[('up', 'Рост'), ('down', 'Падение'), ('same', 'Без изменений')], default='same', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='catalog.offer')),
            ],
            options={
                'indexes': [models.Index(fields=['offer', '-date'], name='idx_price_offer_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.UniqueConstraint(fields=('offer', 'date'), name='uniq_price_offer_date'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(check=models.Q(('price_usd__gte', 0)), name='price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='productdailystat',
            index=models.Index(fields=['date', 'min_price_usd'], name='idx_stat_date_minprice'),
        ),
        migrations.AddIndex(
            model_name='productdailystat',
            index=models.Index(fields=['date', 'trend'], name='idx_stat_date_trend'),
        ),
        migrations.AddConstraint(
            model_name='productdailystat',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='uniq_stat_product_date'),
        ),
    ]
