# Generated by Django 5.0.6 on 2026-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO-код валюты, напр. USD, EUR', max_length=3)),
                ('rate_date', models.DateField()),
                ('rate_uah', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code', '-rate_date'], name='idx_rate_code_date_desc')],
            },
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.UniqueConstraint(fields=('code', 'rate_date'), name='uniq_rate_code_date'),
        ),
    ]
