# Generated by Django 5.0.6 on 2026-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.CheckConstraint(check=models.Q(('rate_uah__gt', 0)), name='rate_positive'),
        ),
    ]
